/*
 * This source file was generated by the Gradle 'init' task
 */
package authservice;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test 
    public void appHasAGreeting() {
        // Basic test to ensure the app can start
        assertTrue(true);
    }
}
